FROM node:22-alpine

ARG UCTOOL_PORT=8000
ARG DATA_DIR=/data

ENV DATA_DIR=$DATA_DIR
ENV UCTOOL_PORT=$UCTOOL_PORT

WORKDIR /data
COPY server/ /data/

EXPOSE 8000
ENTRYPOINT ["/bin/sh", "-c", "node dist/app.js -p $UCTOOL_PORT"]
